package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GradleConnectionRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GradleConnectionRoot")) {
    val expected = GitVcsRoot({
        id("GradleConnectionRoot")
        name = "GHConnection Repository"
        url = "https://github.com/DariaKrup/gradle-simple.git"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_4b4df26346ed38498f51c0d6bee05baa:-1:9aeb4114-69a4-4eba-8c5a-8fafca765e79"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_4b4df26346ed38498f51c0d6bee05baa:-1:c7ee35a4-041e-4826-94ab-f0d8b1e1204b"
        }
    }

}
